# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=200)),
                ('dataSource', models.CharField(max_length=200)),
                ('biteID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtext', models.CharField(max_length=200)),
                ('grid', models.CharField(max_length=10)),
                ('bites', models.ManyToManyField(to='hxldash.BiteConfig')),
            ],
        ),
        migrations.CreateModel(
            name='FilterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='filters',
            field=models.ManyToManyField(to='hxldash.FilterConfig'),
        ),
    ]
