# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biteconfig',
            name='editpassword',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biteconfig',
            name='org',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biteconfig',
            name='user',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biteconfig',
            name='viewpassword',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
