# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0002_auto_20190218_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biteconfig',
            name='editpassword',
        ),
        migrations.RemoveField(
            model_name='biteconfig',
            name='org',
        ),
        migrations.RemoveField(
            model_name='biteconfig',
            name='user',
        ),
        migrations.RemoveField(
            model_name='biteconfig',
            name='viewpassword',
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='editpassword',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='org',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='viewpassword',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
