# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0003_auto_20190218_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardconfig',
            name='subtext',
            field=models.CharField(max_length=2000),
        ),
    ]
