# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0004_auto_20190218_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='color',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
