# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0005_dashboardconfig_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biteconfig',
            name='dataSource',
            field=models.CharField(max_length=2000),
        ),
    ]
