# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0006_auto_20190306_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterconfig',
            name='tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
