# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0008_mapbite'),
    ]

    operations = [
        migrations.AddField(
            model_name='biteconfig',
            name='display',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hxldash.MapBite'),
        ),
    ]
