# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0009_biteconfig_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biteconfig',
            old_name='display',
            new_name='mapOptions',
        ),
        migrations.AddField(
            model_name='mapbite',
            name='scale',
            field=models.CharField(default='linear', max_length=20),
            preserve_default=False,
        ),
    ]
