# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0010_auto_20190613_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardconfig',
            name='editpassword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='org',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='subtext',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardconfig',
            name='viewpassword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
