# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0011_auto_20190613_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='biteconfig',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
