# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0012_biteconfig_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_num', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('dataTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hxldash.dataTable')),
            ],
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='dataTable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hxldash.dataTable'),
        ),
    ]
