# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-30 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hxldash', '0024_auto_20190827_1014'),
        ('hxldash', '0023_auto_20190830_1341'),
    ]

    operations = [
    ]
